replicaCount: 1

deployment:
  name: crud-deployment
  image:
    repo: temperror/otus-chachanagov-hm:5-app
    pullPolicy: Always
  label: crud-java
  initContainer:
    name: init-pg
    image: busybox
  container:
    name: crud-pod-java
    portName: web
    port: 80

service:
  name: crud-service
  label: crud-service-label
  type: NodePort
  protocol: TCP
  portName: service-web
  port: 8000

ingress:
  host: arch.homework
  name: crud-ingress

postgresql:
  fullnameOverride: pg-db
  postgresqlUsername: postgres
  postgresqlPassword: postgres
  postgresqlDatabase: postgres
  service:
    port: "5432"

auth:
  service:
    name: auth-service
    port: 8000
  url: /api/auth/auth
  signin: /api/auth/signin
  path: /api/client

  pathType: Prefix